project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  google-analytics: "G-WPM46XDMMW"
  favicon: "./data/leaf-small.ico"
  title: "LeafSpectroscopy.jl"
  navbar:
    background: primary
    logo: "./data/clima-logo.png"
    left:
      - href: notebooks/intro.ipynb
        text: Home
      - notebooks/about.ipynb
    tools:
      - icon: twitter
        href: https://twitter.com/ewaymao
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/YiweiMao/LeafSpectroscopy.jl
          - text: Report a Bug
            url:  https://github.com/YiweiMao/LeafSpectroscopy.jl/issues
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Background"
        contents:
          - notebooks/intro.ipynb
      - section: "Method"
        contents:
          - notebooks/spectrometers.ipynb
          - notebooks/trigger.ipynb
          - notebooks/walz_pam_programmer.ipynb
      - section: "Tutorials"
        contents:
          - notebooks/tutorial-quarto.ipynb
          - notebooks/tutorial-julia.ipynb
          - notebooks/tutorial-git.qmd
          - notebooks/tutorial-instrument.ipynb
          
  comments: 
    utterances:
      repo: YiweiMao/LeafSpectroscopy.jl

bibliography:
  - refs.bib  

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true